---
title: "Intro"
output: html_notebook
---

## Use R studio or jupyter notebook
1. Download R, Rstudio
https://cloud.r-project.org/
https://www.rstudio.com/products/rstudio/download/
2. Use IRkernel on jupyter notebook

    install jupyter notebook: 
    
    install IRkernel: https://irkernel.github.io/installation/#binary-panel

## Basic R
### Datatype and Operations
1. Datatype conversion: https://www.statmethods.net/management/typeconversion.html
2. Operations:https://www.statmethods.net/management/functions.html

```{r}
library(igraph)
indices <- seq(1,10,2)
y <- rep(1:3, 2)
y.cut <- cut(y, 5)
print(indices)
print(y)
print(y.cut)
```

```{r}
x <- matrix(1:9,3,3)
which(x %% 3 == 0, arr.ind=TRUE)
which(x %% 3 == 0, arr.ind=FALSE)
```

```{r}
x <- c(1:10)
x[(x>8) | (x<5)]
head(x, 1)
tail(x, 1)
typeof(x)
```

## Generate graph

```{r}
p <- 0.1 
# create random graph
g1 <- barabasi.game(100, directed=F)
g2 <- erdos.renyi.game(100, p, directed=F)
# create random graph with given degree distribution
g3 <- degree.sequence.game(rep(2,100))
g <- g1
degree(g)
```

```{r}
plot(g1,vertex.size=8, vertex.label.cex=0.7)
```

```{r}
plot(g2,vertex.size=8, vertex.label.cex=0.7)
```

## Properties

```{r}
is.connected(g)
vcount(g)
ecount(g)
```

```{r}
plot(degree.distribution(g),main="Degree distribution of the network",xlab="Degree",ylab="Frequency")
degreesVector <- degree(g)
hist(degreesVector)
```

## Operations on the graph
    1. Get subgraph
    2. Find GCC
    3. Find shortest path between nodes
    4. Find Communities

```{r}
# http://igraph.org/r/doc/subgraph.html
g <- erdos.renyi.game(1000, p, directed=F)
sub_graph <-induced.subgraph(g,c(1:10))
```

```{r}
V(g)[1:3]
E(g)[1:3]
# Find GCC
g.components <- clusters(g)
print(g.components$csize)
# which is the largest component
ix <- which.max(g.components$csize)
# get the subgraph correspondent to just the giant component
g.giant <- induced.subgraph(g, which(g.components$membership == ix))
```

```{r}
##connected components in the graph
g <- erdos.renyi.game(100, 0.01, directed=F)
is.connected(g)
g.c<-clusters(g)
summary(g.c)
```

```{r}
head(shortest.paths(g, mode = "all"),3)
shortest.paths(g, 1,6)
fg <- fastgreedy.community(g)
cmsize <- sizes(fg)
print(cmsize)
typeof(fg[1])
which(fg$membership == 1)
```

## plot

```{r}
# with given layout
layout <-layout.fruchterman.reingold(g)
plot(g, layout=layout)
```

```{r}
gJ <- graph( c("John", "Jim", "Jim", "Jack", "Jim", "Jack", "John", "John"), 

             isolates=c("Jesse", "Janis"))  

# In named graphs we can specify isolates by providing a list of their names.
plot(gJ, edge.arrow.size=.5, vertex.color="gold", vertex.size=15, 

     vertex.frame.color="gray", vertex.label.color="black", 

     vertex.label.cex=0.8, vertex.label.dist=1, edge.curved=0.2) 
```


